# Generated by Django 5.2.5 on 2025-08-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of location in the garden.', max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_name', models.CharField(help_text='Common name (e.g. Strawberry)', max_length=30)),
                ('variety', models.CharField(blank=True, help_text='Variety name (e.g. Albion)', max_length=30, null=True)),
                ('species', models.CharField(blank=True, help_text='Species (e.g. Fragaria x ananassa)', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of Pot/Container', max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(blank=True, help_text='Brand name of seed', max_length=20, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of seed (e.g. Encinal Nursery, Home)', max_length=20, null=True)),
                ('quantity', models.SmallIntegerField(blank=True, help_text='Quantity of Seed', null=True)),
                ('dt_germ', models.SmallIntegerField(blank=True, help_text='Days to Germination', null=True)),
                ('dt_harv', models.SmallIntegerField(blank=True, help_text='Days to Harvest', null=True)),
                ('purchase_date', models.DateField(blank=True, help_text='Purchase Date', null=True)),
                ('exp_date', models.DateField(blank=True, help_text='Expiration Date', null=True)),
                ('disposed_of', models.BooleanField(default=False, help_text='Has the seed been disposed of.')),
                ('description', models.CharField(blank=True, help_text='Description of seed', max_length=256, null=True)),
                ('plant', models.ForeignKey(help_text='Plant name, variety, species', on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(blank=True, help_text='Brand name of seed', max_length=20, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of seed (e.g. Encinal Nursery, Home)', max_length=20, null=True)),
                ('price', models.FloatField(blank=True, help_text='Cost of plant if purchased retail', null=True)),
                ('purchase_date', models.DateField(blank=True, help_text='Purchase Date if purchased retail', null=True)),
                ('seeding_date', models.DateField(blank=True, help_text='Seeding date if plant was seeded', null=True)),
                ('notes', models.CharField(blank=True, help_text='Notes about planting', max_length=256, null=True)),
                ('location', models.ForeignKey(blank=True, help_text='Location of planting', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.location')),
                ('plant', models.ForeignKey(blank=True, help_text='Plant name, variety, species', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.plant')),
                ('pot', models.ForeignKey(blank=True, help_text='Pot if planted into container', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.pot')),
                ('seed', models.ForeignKey(blank=True, help_text='Seed information if planted from seed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.seed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
